completed assesment
learn-academy-2023-golf/week-3-assessment-amezolaj pull request #1
Opened 2023-10-24 01:16 UTC by amezolaj

# Submitting Week 3 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [ ] Behavioral Questions
- [ ] Career Readiness
- [ ] Coding Challenges
- [ ] Interview Questions
- [ ] React Debugging

### ✋ Reminder

Do NOT merge your assessment!

### 📝 Feedback

If you would like specific feedback please leave details here:

2023-10-25 18:20 UTC, chrisyhlee requested changes
You need to add nuggets in the behavioral-questions file in order to be approved. Other than that, my suggestion for you is to do your due diligence when you find answers to challenges online but you don't understand it. If you look at an answer and are unable to identify the important concepts and then use those concepts to write your own code, that's a good indication that you don't understand it. If you don't understand it, you only do yourself a disservice. This assessment displays Novice, add in nuggets and resubmit in order to be approved.

2023-10-25 18:20 UTC, chrisyhlee commented on behavioral-questions.md
> +- Result:As a result of our hard work and dedication we got a excellent grade and a feature on out morning announcements. This achievement not only validated our creative efforts but also boosted our
You're missing your nugget for both of these

2023-10-25 18:20 UTC, chrisyhlee commented on career-readiness.md
> +Your LinkedIn url: www.linkedin.com/in/jacob-amezola
Keep connecting with people each week

2023-10-26 23:09 UTC, elysemontano approved these changes

2023-10-27 16:08 UTC, merged